name: PEP8 Check

on:
  pull_request:
    branches:
      - main

jobs:
  pep8:
    name: PEP8 Compliance Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run PEP8 check
        run: flake8 --ignore=E501 .

      - name: Comment on pull request
        uses: unsplash/comment-on-pr@v1
        with:
          message: |
            :warning: **PEP8 Check Failed**
            
            The PEP8 check failed. Please make sure your code follows PEP8 style guidelines.

