name: Python Convention Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  conventions:
    name: Check Conventions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6  # Replace 'x' with your desired Python version

      - name: Install dependencies
        run: pip install flake8 black  # You can modify the dependencies to fit your needs

      - name: Run convention checks
        run: |
          git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} -- '*.py' | xargs flake8 --config=flake8.ini --ignore=E501
          git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} -- '*.py' | xargs black --check --diff
