name: Pylint

on:
  pull_request:
    branches:
      - main

jobs:
  code-convention-check:
    name: Code Convention Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Pylint
        run: python -m pip install --upgrade pylint

      - name: Get changed Python files
        id: git_diff
        run: echo "::set-output name=files::$(git diff --name-only --diff-filter=AM '*.py')"

      - name: Run Pylint
        run: |
          for file in ${{ steps.git_diff.outputs.files }}; do
            pylint --disable=all --enable=pylint.extensions.bad_variable_name "$file"
          done
